name: Zarf Lint

on:
  push:
    branches:
      - '!main'
  pull_request:
    branches: [main]

jobs:
  zarf-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.11.6

      - name: Download Zarf Schema
        run: curl -o zarf.schema.json https://raw.githubusercontent.com/defenseunicorns/zarf/main/zarf.schema.json

      - name: Install jsonschema
        run: pip install check-jsonschema==0.28.0

      - name: Validate zarf.yaml If Exists
        run: |
          if [ -f "zarf.yaml" ]; then
            echo "zarf.yaml exists."
            check-jsonschema zarf.yaml zarf-config.yaml --schemafile zarf.schema.json
          else
            echo "zarf.yaml does not exist."
          fi

      - name: Validate zarf-config.yaml If Exists
        run: |
          if [ -f "zarf-config.yaml" ]; then
            echo "zarf-config.yaml exists."
            check-jsonschema zarf-config.yaml zarf-config.yaml --schemafile zarf.schema.json
          else
            echo "zarf-config.yaml does not exist."
          fi